# Tutorial 1: Numpy Practice

## In this tutorial:
- Understand basic numpy code
- Practice using numpy functions
- Simple applications of numpy



If you went through the numpy tutorial posted earlier on the course website, you should be familiar with most of the functions used here. Alternatively, just google each function, or look up "how to ___ using numpy".

In [14]:
import numpy as np

## Part 1: What is the output of each line of code?

Consider the matrices and vectors defined in the cell below. 

#### Write down the output of each of the following lines of code, and then run the cells below to check your answers.

1. elementwise mult

2. argmax on matrix (without axis)

3. argmax on matrix (with axis)

4. argsort on array

5. reverse

6. matmul

7. filtering

8. np.where

9. matrix norm

10. Transpose

In [ ]:
# 1


In [15]:
# 2


In [ ]:
# 3


In [ ]:
# 4


In [ ]:
# 5


In [ ]:
# 6


In [ ]:
# 7


In [ ]:
# 8


In [ ]:
# 9


In [ ]:
# 10


## Part 2: Simple Matrix Manipulation

1. Construct a random 3 × 4 matrix. Call it A. The rows are numbered 0,1,2, and the columns are numbered 0,1,2,3.
2. Construct a random 4-dimensional row vector (that is, a 1 × 4 matrix). Call it x.
3. Reshape A into a 6 × 2 matrix. Call the result B. A itself does not change.
4. Add vector x to all the rows of matrix A. Call the resulting matrix C. C has the same dimensions as A.
5. Reshape x so that is a 4-dimensional vector instead of a 1 × 4 matrix. That is,change its shape from (1,4) to (4). Call the resulting vector y. (Note that y is
6. neither a column vector nor a row vector. We say it has rank 1.)
7. Change row 0 of matrix A to have the same value as vector y.
8. Subtract vector y from row 2 of matrix A and assign the result to row 1 of matrix A. (Only row 1 changes.)
9. Print the first three columns of matrix A as a single matrix.
10. Print rows 0 and 2 of matrix A as a single matrix.
11. Compute the minimum of all the elements in matrix A. The result is a single real number

In [8]:
# 1
A = np.random.random((3,4))
print(A)

[[0.39933059 0.36975363 0.51257679 0.3792366 ]
 [0.53851981 0.92062847 0.98840446 0.15887481]
 [0.36028308 0.13107891 0.93119962 0.93692617]]


In [7]:
# 2
x = np.random.random(4)
print(x)

[0.685831   0.46853394 0.38147114 0.56137831]


In [13]:
# 3
B = A.reshape((6,2))

print("B:\n", B)
print("\nA:\n", A)

B:
 [[0.39933059 0.36975363]
 [0.51257679 0.3792366 ]
 [0.53851981 0.92062847]
 [0.98840446 0.15887481]
 [0.36028308 0.13107891]
 [0.93119962 0.93692617]]

A:
 [[0.39933059 0.36975363 0.51257679 0.3792366 ]
 [0.53851981 0.92062847 0.98840446 0.15887481]
 [0.36028308 0.13107891 0.93119962 0.93692617]]


In [16]:
# 4


In [ ]:
# 5


In [ ]:
# 6


In [ ]:
# 7


In [ ]:
# 8


In [ ]:
# 9


In [ ]:
# 10


In [ ]:
# 11


## Part 3: Applications

1. Vectorization (and measuring runtime)
2. Solving linear systems

### Vectorization

Note that keeping track of how long an iterative process has run can be helpful for predicting how much time is left. For example, print out the ellapsed timeevery 1000 iterations. Or run code on a smaller subset of yyour dataset to see how long it takes, and estimate how long it would take to run on the full dataset (is it linear runtime? quadratic? etc.)

### Sovling linear systems

Later in the course you will probably write this function from scratch, or atleast understand how to. You will also learn how to solve overdetermined systems (where there is no matrix $A$ such that $A\cdot x = b$ for all values of $x$)

In [17]:
import numpy.linalg as la